services:
  db:
    image: postgres:15
    environment:
      PGPORT: ${PGPORT-5432}
      POSTGRES_DB: ${DB_NAME-postly}
      POSTGRES_USER: ${DB_USER-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD-postgres}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    environment:
      PGPORT: ${PGPORT-5432}
      POSTGRES_DB: ${DB_NAME-postly}
      POSTGRES_USER: ${DB_USER-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD-postgres}
    ports:
      - "5433:5432"    # Expose on 5433 locally to avoid conflict
    volumes:
      - pgdata_test:/var/lib/postgresql/data


  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postly
      - JWT_SECRET=super_secret_jwt_key
      - JWT_EXPIRES_IN=1d
    depends_on:
      - pgadmin
      - db

  specs:
    build: .
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postly
      - JWT_SECRET=super_secret_jwt_key
      - JWT_EXPIRES_IN=1d
    depends_on:
      - pgadmin
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "6001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin-data:
  pgdata_test:

