name: Deploy Pipeline

on:
  push:
    branches: [main] # Only triggers on merge to main

jobs:
  ci:
    name: Run CI on main before deploy
    runs-on: ubuntu-latest

    env:
      DB_HOST: db # Usar Secrets
      DB_PORT: 5432
      DB_NAME: postly # Usar Secrets 
      DB_USER: postgres # Usar Secrets
      DB_PASSWORD: postgres # Usar Secrets
      JWT_SECRET: secret_jwt_key
      JWT_EXPIRES_IN: 1d

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose up -d db

          echo "Aguardando PostgreSQL iniciar..."
          until docker exec db pg_isready -U $DB_USER; do
            echo "Esperando DB subir..."
            sleep 2
          done

          echo "Creating Scheme"
          docker exec db psql -U $DB_USER -d $DB_NAME -c "CREATE SCHEMA IF NOT EXISTS blog;"

      - name: Run migrations
        run: docker compose run --rm specs yarn db:migrate

      - name: Run tests with coverage
        run: docker compose run --rm specs yarn test:c

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 324d0484-9057-4ac8-932e-2220ba37d0b9 
          file: ./coverage/lcov.info     

  cd:
    name: Deploy to Render
    needs: ci # 👈 Only runs if CI job above passes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            kainanguerra1/fiap_fase_2:latest

      - name: Trigger Render deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
