name: Specs Pipeline

on:
  pull_request: # Run CI on PR branches
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build -f Dockerfile.specs -t test-runner .

      - name: Run lint
        run: docker run --rm test-runner npm run lint

      - name: Run tests
        run: docker run --rm test-runner npm run test
