name: Specs Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Database
        run: docker compose run --rm specs yarn db:spawn

      - name: Run tests with coverage
        run: docker compose run --rm specs yarn test:c
    
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 324d0484-9057-4ac8-932e-2220ba37d0b9 
          file: ./coverage/lcov.info     

