name: Specs Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DB_HOST: db-test
      DB_PORT: 5432
      DB_NAME: postly 
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: secret_jwt_key
      JWT_EXPIRES_IN: 1d

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Run migrations
        run: docker compose run --rm specs yarn db:spawn

      - name: Run tests with coverage
        run: docker compose run --rm specs yarn test:c

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 324d0484-9057-4ac8-932e-2220ba37d0b9 
          file: ./coverage/lcov.info  
