name: CI

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Build and run tests from Dockerfile.specs
        run: |
          docker build -f Dockerfile.specs -t test-runner .
          docker run --rm test-runner

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push production image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            kainanguerra1/fiap_fase_2:v1
            kainanguerra1/fiap_fase_2:latest
