name: Testes com Docker Compose

on:
  push:
    branches: [criacao-testes]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    env:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: secret_jwt_key
      JWT_EXPIRES_IN: 1d
      PGADMIN_DEFAULT_EMAIL: ${{secrets.USER}}
      PGADMIN_DEFAULT_PASSWORD: ${{secrets.PASSWORD}}
      PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose up -d db

          echo "Aguardando PostgreSQL iniciar..."
          until docker exec db pg_isready -U $DB_USER; do
            echo "Esperando DB subir..."
            sleep 2
          done

          echo "Creating Scheme"
          docker exec db psql -U $DB_USER -d $DB_NAME -c "CREATE SCHEMA IF NOT EXISTS blog;"

      - name: Run migrations
        run: docker compose run --rm specs yarn db:migrate

      - name: Run tests with coverage
        run: docker compose run --rm specs yarn test:c

      - name: List coverage directory
        run: ls -al ./coverage
    
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: ./coverage/lcov-report/lcov.info     

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down -v
